name: A workflow for my Hello World file New
on: push
jobs:
  build:
    name: Hello world action New
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Dharmesh"
